### ISSUE TITLE
Why does this need to be an async function?

### ISSUE THREAD

**Issue by pke** [danmichaelo/cordova-plugin-appinfo#10]
Is there a reason why this was implemented in an async fashion?
Couldn't `navigator.appInfo` be set during plugin initialization?

**Comment by danmichaelo** [comment]
I guess it could. Not sure when the information is available though, perhaps at `deviceready`? Could there be a race condition if the plugins sets the information at `deviceready` and some user code expects `navigator.appInfo` to be available at `deviceready`?

**Comment by pke** [comment]
Its a common pattern, that cordova plugins are only fully working after the `deviceReady` event has been fired. So I think we could introduce `cordova.plugins.appInfo` without breaking any of the existing users of the plugin.

**Comment by danmichaelo** [comment]
Yeah, but the problem I see is that if this plugin fills `navigator.appInfo` on `deviceready`, that information will not actually be available for others to read when `deviceready` fires, but at least one turn later.. And how should users know when `navigator.appInfo` has actually been populated? Ideally I guess `navigator.appInfo` should already be populated at the moment `deviceready` fires, but I do not know the cordova system well enough to say if there is a way to do that (perhaps by hooking into some other event). Could look into how other plugins do similar things, but I don't have a lot of time to put into this. If you can find an example of how it's done in a similar plugin (which works well :)), let me know. A pull request is of course also welcome.

**Comment by pke** [comment]
No, you fill the info **before** `deviceReady` is fired. Look at the cordova device plugin how they do it. 

`deviceReady` is only fired after all plugins have been loaded. Plugins are loaded async so you can do whatever you need to do to fill up `appInfo` and then tell cordova that you are ready. Once all plugins signaled they are ready, cordova fires `deviceReady`.

**Comment by danmichaelo** [comment]
Ok, that's good. Having a look at [device.js](https://github.com/apache/cordova-plugin-device/blob/master/www/device.js), I see that the device plugin registers to some `onCordovaReady` method and calls `onCordovaInfoReady` when done. Do you know if this stuff is documented anywhere?

**Comment by pke** [comment]
Haven't found any docs on it yet. But it seems we could just model it like they do it in the device plugin.
