### ISSUE TITLE
How do I use with Phonegap Desktop please?

### ISSUE THREAD

**Issue by elckerlyc** [danmichaelo/cordova-plugin-appinfo#15]
I have not been able to get this working yet.
I tried in config.xml :
<plugin name="cordova-plugin-appinfo" source="npm" spec="~2.1.2" />

Or do I have to do something with cli first? Haven't been needing to do so, so far.
Sorry for dumb question.

**Comment by danmichaelo** [comment]
I don't know Phonegap Desktop, but installation should be the same as other plugins. Did you manage to install any other plugin? If not, try to search for general plugin install instructions.

**Comment by elckerlyc** [comment]
Yes, I used other plugins, hence the question.
Thanks

**Comment by danmichaelo** [comment]
If you could also mention one or more plugins you were able to install, I could perhaps try to check how they are packaged compared to this one.  And as always when reporting issues, if there's any additional information you can provide, like error messages, logs, please do so.

**Comment by elckerlyc** [comment]
examples that work (in config.xml):
```
<gap:plugin name="cordova-plugin-x-socialsharing" source="npm" />
<plugin name="cordova-plugin-inappbrowser" source="npm" spec="~1.3.0" />
```
The respective functions are then implemented in js in the onDeviceReady function thus:
`window.open = cordova.InAppBrowser.open;`

and in the index.htm:

`<button  onclick="window.plugins.socialsharing.share('ISome text', 'A Title', 'an Image', 'a Link')">`

No further installation is required by phonegap, this works just fine.
But: the cordova-plugin-appinfo does not work at all, and I tried all examples I could find.
Thanks for any help.

**Comment by danmichaelo** [comment]
Ok, sory to hear that. It's been a while since I worked with this stuff, so could be that there's a incompability with Phonegap Desktop
