### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by roberthovhannisyan** [danmichaelo/cordova-plugin-appinfo#5]
Hi @danmichaelo ,

I (and hopefully many other users) would be grateful if you consider publishing this useful plugin to npm.
The steps are described here: http://cordova.apache.org/announcements/2015/04/21/plugins-release-and-move-to-npm.html

**Comment by danmichaelo** [comment]
Added. Let me know if it works, I don't work with cordova at the moment.

(Guess I should also try to merge in some changes from https://github.com/yezhiming/cordova-plugin-appinfo now)

**Comment by roberthovhannisyan** [comment]
Thanks a lot @danmichaelo
It woud be great also to see latest changes from @yezhiming !

**Comment by danmichaelo** [comment]
Yeah, I make a separate issue on it
